<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<link href="//fonts.googleapis.com/css?family=Montserrat:400,700|Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet"> 
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left col-md-5 col-sm-5 col-xs-12">
						<?php echo $this->getChildHtml('welcometop'); ?>
					</div>
					<div class="top-right col-md-7 col-sm-7 col-xs-12">
						<div class="header-setting">
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<div class="text-setting"><?php echo __('Links'); ?></div>
								</div>
								<div class="dropdown-switcher toggle-content">
									<?php echo $this->getChildHtml('currency'); ?>
								    <?php echo $this->getChildHtml('store_language'); ?>
								</div>
							</div>
							<div class="top-links">
							     <?php echo $this->getChildHtml('header.links'); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content header-sticker">
			<div class="container">
				<div class="row">
					<div class="content-logo col-md-2 col-sm-2 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-lg-12 header-right menu-mobile">
						<div class="content-cart pull-right">
						   <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
							<?php echo $this->getChildHtml('minicart'); ?>
						</div>
						<div class="header-setting content-seach">
							<div class="settting-switcher header-search">
								<div class="dropdown-toggle"><div class="icon-setting"><i class="icon-magnifier icons"></i></div></div>
								<div class="dispaly-seach dropdown-switcher">
									<div class="search-area header-search">
										<?php echo $this->getChildHtml('top.search'); ?>
									</div>
								</div>
						    </div>
						</div>
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
