<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-copyright">
<div class="container">
		<div class="main">		
			<div class="copyright">
					<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
				</div>
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-payment')->toHtml();?>
			</div>
		</div>	
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>