<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */ 
?>
<link href="//fonts.googleapis.com/css?family=Montserrat:400,700|Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet"> 
<header class="page-header alothemes">
    <div class="header header-sticker">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-social')->toHtml();?>
					</div>
					<div class="top-right header-setting">
						<div class="settting-switcher">
							<span class="toggle-tab">
								<i class="pe-7s-config"></i>
								<span><?php echo __('Settings'); ?></span>
							</span>
							<div class="dropdown-switcher toggle-content">
								<?php echo $this->getChildHtml('currency'); ?>
								<?php echo $this->getChildHtml('store_language'); ?>
							</div>
						</div>
						<div class="header-wishlist">
						<a title="<?php echo __('Wishlist') ?>" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="wishlist icon icon-favorites">
							<i class="pe-7s-like"></i><span><?php echo __('Wishlist') ?></span>
								</a>
						</div>						
						<div class="top-links">
						<span class="toggle-tab"><i class="pe-7s-user"></i><span><?php echo __('My account'); ?></span></span>
						<div class="toggle-content">
						<?php echo $this->getChildHtml('header.links'); ?>
						</div>						
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container">
				<div class="row">
					<div class="menu-mobile">
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
					</div>
					<div class="content-seach">
						<span class="toggle-tab"><span class="pe-7s-search"></span></span>
						<div class="search-area header-search toggle-content">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
					<div class="content-logo">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="content-cart">					  
						<?php echo $this->getChildHtml('minicart'); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom">
			<div class="container">
				<div class="row">
				<?php echo $this->getChildHtml('navigation.sections'); ?>
				</div>				
			</div>
		</div>
	</div>
</header>
